# 生产环境的重点是效率和性能，所以通常会用 Nginx 来提供静态文件服务，并且不需要热加载。
# 构建阶段
FROM node:18 as build

# 创建应用目录
WORKDIR /frontend

# 复制代码到容器中
COPY . .

# 安装依赖并构建应用
RUN yarn install
RUN yarn build

# 部署阶段
FROM nginx:1.23-alpine

# 将构建生成的静态文件复制到 Nginx 的默认目录
COPY --from=build /frontend/build /usr/share/nginx/html

# 如果有特定的 nginx 配置文件可以覆盖默认配置
COPY ./conf.d/prod.conf /etc/nginx/conf.d/default.conf

# 暴露 Nginx 的默认端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
