version: '3.5'

name: yolotester_prod

services:
  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    depends_on:
      - redis

  celery:
    # image: ship:celery
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: python3 celery_worker.py
    volumes:
      - ./backend:/backend
    environment:
      - UDEV=1
      - MINIO_ACCESS_KEY=SlDE1OdZIQpyOairqTer
      - MINIO_SECRET_KEY=zzkVFBZ4akPLdeGaKuMWdgyCpCCrqrbA5vmuIGia
      - NVIDIA_VISIBLE_DEVICES=all  # 让容器可以访问所有 GPU
      - NVIDIA_DRIVER_CAPABILITIES=all  # 让容器具有完整的 GPU 功能（包括计算、视频等）
      - RESULT_DIR=/tmp/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # 你可以指定具体的 GPU 数量，例如 '1' 只使用1个GPU
              capabilities: [gpu]
    runtime: nvidia

  backend:
    # image: lyl472324464/ship:backend-amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8000"
    command: sh -c "python3 main.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    privileged: true
    working_dir: /backend
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - UDEV=1
      - MINIO_ACCESS_KEY=SlDE1OdZIQpyOairqTer
      - MINIO_SECRET_KEY=zzkVFBZ4akPLdeGaKuMWdgyCpCCrqrbA5vmuIGia
      - DEFAULT_BUCKET=yolo-files
      # - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    depends_on:
      # tritonserver:
      #   condition: service_started
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    runtime: nvidia

  frontend:
    # image: ship:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # 生产环境下前端不能跟着代码变化
    # volumes:
    #   - ./frontend:/frontend
    restart: always
    # command: bash -c "nginx && yarn start"
    command: bash -c 'nginx -g "daemon off;"'
    ports:
      - 80:80
    depends_on:
      - backend

  minio:
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: http://minio:9000
      DEFAULT_BUCKET: yolo-files
      # MINIO_BROWSER_REDIRECT_URL: http://localhost:9092
      # MINIO_BROWSER_REDIRECT_URL: http://192.168.1.10/minio/ui
    command: server --console-address ":9090" /data
    ports:
      - "9000"
      - "9090:9090"
    volumes:
      - ./minio/prod_data:/data

  loki:
    image: grafana/loki:2.6.1
    user: "10001:10001"
    ports:
      - "3100"
    volumes:
      # directory must be created first, with uid:gid 10001:10001
      - ./volumes/prod_loki:/loki

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      # custom config will read logs from the containers of
      # this project
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

  # will be available at http://127.0.0.1:3000
  # default credentials: admin/admin
  grafana:
    image: grafana/grafana:9.2.2
    user: "472:472"
    ports:
      - "3010:3010"
    volumes:
      # directory must be created first, with uid:gid 472:472
      - ./volumes/grafana:/var/lib/grafana
      # automatically configure the loki datasource
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6379"

  mongo:
    image: mongo:7.0.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db